import os
import sys
from typing import List, Dict, Any
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

class VectorDBManager:
    """Handles vector collection creation, insertion, and similarity search."""

    def __init__(self, storage_path: str = "./data/qdrant_storage", collection_name: str = "ai_fingerprints", vector_size: int = 384):
        self.collection_name = collection_name
        self.vector_size = vector_size
        
        # Initialize embedded Qdrant client stored locally on disk
        self.client = QdrantClient(path=storage_path)
        self._ensure_collection()

    def _ensure_collection(self):
        """Creates collection if it does not already exist."""
        collections = [col.name for col in self.client.get_collections().collections]
        if self.collection_name not in collections:
            self.client.create_collection(
                collection_name=self.collection_name,
                vectors_config=VectorParams(size=self.vector_size, distance=Distance.COSINE)
            )
            print(f"Created Qdrant collection: {self.collection_name}")

    def upsert_fingerprints(self, ids: List[int], vectors: List[List[float]], payloads: List[Dict[str, Any]]):
        """Stores fingerprint vectors and metadata into Qdrant."""
        points = [
            PointStruct(id=idx, vector=vec, payload=payload)
            for idx, vec, payload in zip(ids, vectors, payloads)
        ]
        self.client.upsert(collection_name=self.collection_name, points=points)
        print(f"Successfully upserted {len(points)} points into '{self.collection_name}'.")

    def search_similar(self, query_vector: List[float], top_k: int = 2) -> List[Dict[str, Any]]:
        """Finds top-K most similar text fingerprints."""
        response = self.client.query_points(
            collection_name=self.collection_name,
            query=query_vector,
            limit=top_k
        )
        return [
            {"id": hit.id, "score": round(hit.score, 4), "payload": hit.payload}
            for hit in response.points
        ]

    def close(self):
        """Explicitly closes the local storage client connection."""
        if hasattr(self, 'client') and self.client is not None:
            self.client.close()

if __name__ == "__main__":
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
    from training.embedder import TextEmbedder

    embedder = TextEmbedder()
    db = VectorDBManager()

    texts = [
        "LLMs generate repetitive stylistic patterns.",
        "Human writing displays variable burstiness and perplexity.",
        "Deep learning transformer models produce text fingerprints."
    ]
    vectors = embedder.embed_texts(texts)
    payloads = [{"text": t, "author": "sample"} for t in texts]

    db.upsert_fingerprints(ids=[1, 2, 3], vectors=vectors, payloads=payloads)

    query_text = "How to detect text generated by AI transformers?"
    query_vector = embedder.embed_texts([query_text])[0]
    matches = db.search_similar(query_vector, top_k=2)

    print("\n--- Similarity Search Results ---")
    for match in matches:
        print(f"Score: {match['score']} | Text: {match['payload']['text']}")

    # Clean connection close
    db.close()